---
- name: delete osd disk partition
  shell: ceph-deploy disk zap "{{item}}":sda
  with_items:
    - "node1"
    - "node2"
    - "node3"
  args:
    chdir: ~/cluster
- name: purge node
  shell: ceph-deploy purge "{{ item }}"
  with_items:
    - "node1"
    - "node2"
    - "node3"
  args:
    chdir: ~/cluster
- name: purge node data
  shell: ceph-deploy purgedata "{{ item }}"
  with_items:
    - "node1"
    - "node2"
    - "node3"
  args:
    chdir: ~/cluster
- name: remove keys
  shell: ceph-deploy forgetkeys
  args:
    chdir: ~/cluster
- name: remove ceph related files
  file:
    path: "{{item}}"
    state: absent
  with_fileglob:
    - ceph.*
  args:
    chdir: ~/cluster
